require:
  - rubocop-rails
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 23
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
Rails/FilePath:
  Exclude:
    - config/environments/*
Metrics/AbcSize:
  Max: 23
Layout/LineLength:
  Max: 120
Rails/BulkChangeTable:
  Exclude:
    - db/migrate/*
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
Style/Documentation:
  Enabled: false
